CXX = g++
CXXFLAGS = -Wall -std=c++11

#Pack.o: Pack.h
#	$(CXX) $(CXXFLAGS) -c $^ -o $@

all : clean

# main: main.o Tile.o Square.o
# 	$(CXX) $(CXXFLAGS) $^ -o $@

# client: client.o Tile.o Square.o 
# 	$(CXX) $(CXXFLAGS) $^ -o $@

clean:
	rm *.o
